name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Moul
        run: curl -s https://moul.app/install.sh | bash
        env:
          SHELL: bash

      - name: Build Site
        run: moul export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ellagross.de
          commit_message: ${{ github.event.head_commit.message }}
